In [1]:
### By using the Keras Libraray

In [2]:
import numpy as np
import pandas as pd


In [3]:
## After that creating our own dataset
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['CGPA','PROFILE_SCORE','LPA'])

In [4]:
## Now see our dataset
df.head()

CGPA  PROFILE_SCORE  LPA
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [5]:
## Now the next imp part , importing the keras library
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [10]:
## Now storing object into variable
model = Sequential()
model.add(Dense(2,activation='linear', input_dim=2)) ## This is the input layer 
model.add(Dense(1,activation='linear'))
import warnings
warnings.filterwarnings('ignore')

In [11]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape          ┃      Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ dense_5 (Dense)               │ (None, 2)             │            6 │
├───────────────────────────────┼───────────────────────┼──────────────┤
│ dense_6 (Dense)               │ (None, 1)             │            3 │
└───────────────────────────────┴───────────────────────┴──────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.get_weights()

[array([[-1.1070821 , -0.10502756],
        [ 0.3731674 ,  0.4381107 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.8690707],
        [ 1.1716007]], dtype=float32),
 array([0.], dtype=float32)]

In [13]:
new_weights=[np.array([[0.1,0.1],
                     [0.1,0.1]], dtype=np.float32),
            np.array([0.,0.], dtype=np.float32),
            np.array([[0.1],[0.1]], dtype=np.float32),
            np.array([0.], dtype=np.float32)]

In [14]:
model.set_weights(new_weights)

In [15]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [16]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error", optimizer=optimizer)

In [17]:
model.fit(df.iloc[:,0:-1].values, df['LPA'].values, epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 27.8873 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 27.5797
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 27.2315
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.9036 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 26.5665
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26.1958
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25.8308
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.4455
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25.0719
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 24.6275 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24.2279
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 23.7953 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 23.3645
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22.9459
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.5074 
Epoch 16/75
4/4 ━━

In [18]:
model.get_weights()

[array([[0.37344632, 0.37344632],
        [0.36558798, 0.36558798]], dtype=float32),
 array([0.2722264, 0.2722264], dtype=float32),
 array([[0.37283888],
        [0.37283888]], dtype=float32),
 array([0.20476972], dtype=float32)]